version: '3.9'

services:
  app:
    container_name: yandex_api_mega_market
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:8000"
    restart: always

  db:
    image: postgres:13.4-alpine3.14
    container_name: yandex_data_mega_market
    env_file:
      - .env.example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./psql:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "22:5432"